### ISSUE TITLE
Selecting a new web login favorite does not auto-logout previous selection with Firefox

### ISSUE THREAD

**Issue by agraveskion** [kionsoftware/kion-cli#29]
This issue has previously been resolved for Chrome users.
Firefox users are still experiencing this issue.

If a user is working between multiple AWS web console favorite selections, the second and subsequent favorite selections will redirect to the AWS console screen that prompts the user to log out of the existing session before attempting to log in. 
Ideally, the Kion CLI should close existing sessions when opening a new web console session.

**Comment by codybuell** [comment]
Just to confirm, this has been tested on the latest from the master branch?

**Comment by codybuell** [comment]
> Just to confirm, this has been tested on the latest from the master branch?

Confirmed on my system.

**Comment by codybuell** [comment]
PR is being reviewed. The problem lies in how Firefox handles headers from AWS, preventing use from using an iframe to handle closing a console session before starting another. The workaround uses tabs instead of an iframe on Firefox browsers only. The one gotcha is that it is treated as a pop-up and will have to be approved on the first run. Subsequent runs should go through with no problems. Once the PR is in pull and rebuild from the main branch.

**Comment by sculliga** [comment]
I confirmed the fix does work, but I wanted to share if you think it would help improve this process.

AWS supports calling the logout URL with a redirect URI where you can pass the federation URL.

I'm unfamiliar with Go, but here is an example from Python to construct the URL. I believe this would simplify logging out and opening the login URL. I think this is what AWS's IAM Identity Center SSO does behind the scenes.

Kion could also theoretically do this when supplying the URL from `/api/v1/console-access`

```python
import re
from urllib.parse import quote_plus

# Sign-in URL from /api/v1/console-access
url = 'https://signin.aws.amazon.com/federation?Action=login&Destination=https%3A%2F%2Fus-east-1.console.aws.amazon.com%2F&SigninToken=<token_here>'

# Replace the region in the URL to us-east-1 to support redirect_uri since the generic signin URL without a region does not support it
url = re.sub(r':\/\/signin', '://us-east-1.signin', url)

# Encode the URL
url = quote_plus(url)

# Generate the logout endpoint
logout_endpoint = f"https://signin.aws.amazon.com/oauth?Action=logout&redirect_uri={url}"

# Open the federation URL in the browser
print(logout_endpoint)
```

Which would generate something like this
```
https://signin.aws.amazon.com/oauth?Action=logout&redirect_uri=https%3A%2F%2Fus-east-1.signin.aws.amazon.com%2Ffederation%3FAction%3Dlogin%26Destination%3Dhttps%253A%252F%252Fus-east-1.console.aws.amazon.com%252F%26SigninToken%3D%3Ctoken_here%3E
```
