### ISSUE TITLE
Support for multiple instances of Kion

### ISSUE THREAD

**Issue by matty52** [kionsoftware/kion-cli#41]
We manage multiple instances of Kion due to having multiple environments (e.g. dev. test, prod) and customers. This results in us maintaining multiple ```.kion.yml``` config files, which becomes cumbersome and prone to human error when switching between customers/environments. 
Is it possible to add support for multiple Kion instances? 
For example,  adding a ```--config-file  FILE``` flag:
``` kion stak --config-file ~/.kion.yml.dev --account 121212121212 --car Admin```
``` kion stak --config-file ~/.kion.yml.prod --account 2323232323 --car Admin```

**Comment by codybuell** [comment]
Hey @matty52, thanks for the feature request. We have the need for this as well internally. My initial thought was to add multiple profiles within the `~/.kion.yml` configuration file and do something similar to the AWS CLI profiles, eg `--profile prod`. Any thoughts on that vs maintaining separate configuration files? May be able to implement both actually.

**Comment by matty52** [comment]
Yeah, multiple profiles in the ```~/.kion.yml``` would work as well. I only mentioned the ```--config-file``` flag as an example to ensure the feature request was well understood. I'm not partial to any specific implementation.

**Comment by codybuell** [comment]
@matty52 The linked PR is ready for testing, if you are able to give it a go let me know if you bump into any issues. See the updated README.md on that branch for usage info.
