### ISSUE TITLE
[question] SAML auth integration with kion-cli

### ISSUE THREAD

**Issue by jzhn** [kionsoftware/kion-cli#45]
# Context

Hi, Kion CLI maintainers, I'm very excited to find out this project as it's been a source of pains and mistakes for cloud/platform engineers at my org having to copy-paste AWS temporary credentials from Kion website. The compatibility of aws credentials process makes Kion CLI a perfect fit for my org.

I understand that Kion CLI supports API Key, Password and SAML integration. I hope to use SAML as it allows SSO integration with our Azure AD IDP without saving long lived password/keys locally.

# Problem

I understand that Kion-cli works with SAML by launching a `localhost:8400` endpoint to proxy the SAML callback. With a few tweaks at my Azure AD SAML IDP configuration, I'm able to make both the SAML IDP and SP happy with this proxy in between. However, I went into trouble with a few Kion APIs that the CLI is calling. 

Particularly:
- `GET /api/v2/csrf-token` - always returns 401 (called at https://github.com/kionsoftware/kion-cli/blob/v0.3.0/lib/kion/saml.go#L322)
- `POST /api/v1/saml/callback` - it returned the `auth_token` and `refresh_token` directly, instead of an `sso_code` that the cli is expecting at https://github.com/kionsoftware/kion-cli/blob/v0.3.0/lib/kion/saml.go#L165
- `GET /api/v2/login/sso-provider` - since SAML callback returns `auth_token` directly, this API can be skipped.

I did manage to make the SAML integration work end-to-end after tweaking Kion-CLI in my branch: https://github.com/jzhn/kion-cli/pull/1/files,  which basically works around above API spec differences that I discovered.

My wild guess is that either Kion-CLI is targeting an unreleased newer version of Kion that have different API specs, or my current Kion version (`3.7.9`) is too old for it.

I also understand that Kion-cli is newly released in less than a month. So it might not be production ready. So any additional advice is appreciated, like
- production readiness?
- compatibility matrix?

# Notes

## Version

- kion-cli: tried both v0.3.0 and latest main branch
- kion: 3.7.9

**Comment by codybuell** [comment]
Hi @jzhn, thanks for the well written issue! We'll take a look and get back to you shortly.

**Comment by bdljohnson** [comment]
Thanks for the issue @jzhn - the flow for SAML changed with 3.8.0 to be cookie-based as you discovered. We can add some backwards compatibility here.

**Comment by jzhn** [comment]
Thanks @bdljohnson and @codybuell ! We'll plan for 3.8.x upgrade, but adding compatibility to 3.7.x would be great too, since it's still an [officially supported version](https://support.kion.io/hc/en-us/articles/4422738511501-Supported-Versions) of Kion. I'll keep my forked PR (https://github.com/jzhn/kion-cli/pull/1/files) open in case it helps with the compatibility update.

**Comment by codybuell** [comment]
@jzhn The fix has been merged in. If you installed with homebrew you can do an update and upgrade to pull the latest version.

```bash
brew update
brew upgrade kion-cli
```

**Comment by jzhn** [comment]
thank you @codybuell ! I can confirm that `kion stak` and `kion console` works for my Kion v3.7.x instance with Azure AD SAML IDP.
