### ISSUE TITLE
alias usage

### ISSUE THREAD

**Issue by juweeks** [kionsoftware/kion-cli#59]
looking at the readme and don't seem to understand how to use the alias arg. what is it? does it go in kion.yml? tried using the AWS account alias, and other names in Kion and that didn't work. thanks!

**Comment by codybuell** [comment]
Hi @juweeks, I need to get an update into the readme, but alias support is only available in Kion 3.9.9 or 3.10.2 and up. If you're on one of those versions or later let me know and we can dig in. Also alias support is only available via flags at the moment.

**Comment by juweeks** [comment]
ah ok. good to know. thanks @codybuell
