### ISSUE TITLE
error when trying to use a profile

### ISSUE THREAD

**Issue by juweeks** [kionsoftware/kion-cli#66]
when trying to use an alternate profile: `kion console --profile altprofile`
returns: `Incorrect Usage: flag provided but not defined: -profile`

when the default profile is removed, it prompts for a Kion URL

**Comment by codybuell** [comment]
Hi @juweeks, the `--profile` flag is a global configuration so it has to be placed in front of the intended command:

```bash
kion --profile altprofile console
```

Otherwise it thinks you are providing the `--profile` flag the `console` command.

**Comment by juweeks** [comment]
Got it! Thanks ..
