### ISSUE TITLE
403 error when using stak

### ISSUE THREAD

**Issue by sixth** [kionsoftware/kion-cli#7]
Hello,

first off, thank you for creating this!

i'm receiving the 403 error below when using the `stak` command. however, when manually listing accounts as favorites in `~/.kion.yml` and using the `fav` command, everything works fine. i assume it has to do with permissions, but when first running the `stak` command, i am able to see all the projects i have access to.

```
e@mbp kion-cli % 
e@mbp kion-cli % kion stak

 Choose a project: dev
 Error: received 403
 {"status":403,"message":"Insufficient permission to view project accounts"}

e@mbp kion-cli % 
```

**Comment by codybuell** [comment]
@sixth thanks for opening the issue. Yeah it sounds like a permissions configuration issue. Can you take a look and let me know what permissions you have on the `dev` project?

**Comment by sixth** [comment]
doesn't seem like i have access to view my permissions? attaching screenshots of the webUI below;

![Screenshot 2024-02-22 at 14 36 50](https://github.com/kionsoftware/kion-cli/assets/11591445/54b36b0a-ec22-4158-806c-c9c82bb00b9c)
![Screenshot 2024-02-22 at 14 37 50](https://github.com/kionsoftware/kion-cli/assets/11591445/ffae2932-4100-449a-96c2-7223d4ea8eff)

**Comment by codybuell** [comment]
Thanks for the screenshots. We were able to replicate the issue here. Take a look at [this branch](https://github.com/kionsoftware/kion-cli/tree/7-workaround-inconsistent-permission-check), if you are able to pull that down and give it a go let me know if it resolves it on your end.

**Comment by codybuell** [comment]
The fix has been merged into main. Let me know if the problem persist.

**Comment by sixth** [comment]
that was fast! confirming it works on my end as well. thanks again
